### PR TITLE
CASMTRIAGE-3280: Wait for a quorum of nodes to join before applying network manifests

### PR DESCRIPTION
**Pull request by johren-hpe**
#### Summary and Scope

- Fixes # CASMTRIAGE-3280

##### Issue Type

- Bugfix Pull Request

We tracked down the root cause of weave split-brain on gamora.  The issue was caused by weave pods starting up before enough of the nodes have joined the cluster.   More details in https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3280.   To fix this, we are waiting for a quorum of nodes to join the cluster before applying the network manifests.   We tried this process manually on gamora and we were able to see the expected results in the weave logs showing that they had a enough peers in the peer list to avoid splitting the two masters into two separate seed groups.

#### Prerequisites

- [N/A] I have included documentation in my PR (or it is not required)
- [ ] I tested this on metal (e.g. an internal system, with hardware) (x) (if yes, please include results or a description of the test)
- [ ] I tested this on vshasta (if yes, please include results or a description of the test)
 
 
#### Risks and Mitigations
 
This code will be smoke tested on gamora to mitigate risk.

### CODE REVIEW

**Review by bklei — DISMISSED** [review]

**Review by heemstra — DISMISSED** [review]

**Review by rustydb — APPROVED** [review]

**Comment by rustydb** [comment]
I've rebased this since #266 went in.

**Review by heemstra — APPROVED** [review]

**Comment by rustydb** [comment]
Awaiting smoke test results on gamora.

**Comment by rustydb** [comment]
Rebased this because #272 merged.

**Review by rustydb — DISMISSED** [review]

**Comment by rustydb** [comment]
This hit a failure on gamora, @johren-hpe is working on an update/fix.

**Pull request merged**
