### PR TITLE
VSHA-361: Add new step to call Jenkins job that runs tests

### PR DESCRIPTION
**Pull request by thiagonache**
#### Summary and Scope
As per title

### CODE REVIEW

**Comment by thiagonache** [comment]
The job just failed because the pitnode image is not being built in the develop branch. Once we merge the branch with pitnode image it will work.

**Review by heemstra — APPROVED** [review]

**Review by manderson-hpe — APPROVED** [review]

**Comment by rustydb** [comment]
> /fast -forward

Branch is in need of an update.

**Review by rustydb — APPROVED** [review]

**Comment by rustydb** [comment]
I've updated the branch.

**Pull request closed without merging**
